"""Deletar_tabela_products

Revision ID: f8a38fae484c
Revises: c0c49eb94027
Create Date: 2025-10-12 15:29:10.593515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8a38fae484c'
down_revision: Union[str, None] = 'c0c49eb94027'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('cod_sistema', sa.INTEGER(), nullable=False),
    sa.Column('cod_pdv', sa.VARCHAR(length=20), nullable=False),
    sa.Column('categoria', sa.VARCHAR(length=30), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=80), nullable=False),
    sa.Column('preco_custo', sa.FLOAT(), nullable=False),
    sa.Column('preco_venda', sa.FLOAT(), nullable=False),
    sa.Column('medida', sa.VARCHAR(length=2), nullable=False),
    sa.Column('estoque', sa.INTEGER(), nullable=False),
    sa.Column('estoque_min', sa.INTEGER(), nullable=False),
    sa.Column('sit_estoque', sa.VARCHAR(length=50), nullable=False),
    sa.Column('descricao', sa.VARCHAR(length=300), nullable=False),
    sa.Column('ficha_tecnica', sa.VARCHAR(length=300), nullable=True),
    sa.Column('status_venda', sa.VARCHAR(length=20), nullable=False),
    sa.Column('imagem_url', sa.VARCHAR(length=300), nullable=True)
    , sa.PrimaryKeyConstraint('cod_sistema')
    )
