services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/backend  # host:container
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/deliverydb
            - APP_NAME=pdv-system
      - PROMETHEUS_PREFIX=fastapi
      - PROMETHEUS_ENABLED=true
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules # host:container
    ports:
      - "5173:5173"
    depends_on:
      - backend

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: deliverydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
