"""auteração banco de dados

Revision ID: 43b331aa0e7d
Revises: 2e5a7eb65f22
Create Date: 2025-12-21 20:58:39.773588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '43b331aa0e7d'
down_revision: Union[str, None] = '2e5a7eb65f22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produtos')
    op.drop_index('ix_clientes_id', table_name='clientes')
    op.drop_table('clientes')
    op.drop_index('ix_pedidos_id', table_name='pedidos')
    op.drop_table('pedidos')
    op.drop_table('caixa')
    op.drop_index('ix_itens_pedidos_id', table_name='itens_pedidos')
    op.drop_table('itens_pedidos')
    op.drop_table('carrinhos')
    op.drop_table('categorias')
    op.drop_index('ix_enderecos_pedidos_id', table_name='enderecos_pedidos')
    op.drop_table('enderecos_pedidos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enderecos_pedidos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pedido_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cep', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('endereco', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('numero', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bairro', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('cidade', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('estado', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('complemento', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('referencia', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('taxa_entrega', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], name='enderecos_pedidos_pedido_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='enderecos_pedidos_pkey'),
    sa.UniqueConstraint('pedido_id', name='enderecos_pedidos_pedido_id_key')
    )
    op.create_index('ix_enderecos_pedidos_id', 'enderecos_pedidos', ['id'], unique=False)
    op.create_table('categorias',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('categorias_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='categorias_pkey'),
    sa.UniqueConstraint('nome', name='categorias_nome_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('carrinhos',
    sa.Column('produto_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cod_pdv', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('categoria', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('preco_custo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('preco_venda', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('medida', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('estoque', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('estoque_min', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sit_estoque', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('ficha_tecnica', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('status_venda', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('imagem_url', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('quantidade', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('produto_id', name='carrinhos_pkey')
    )
    op.create_table('itens_pedidos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pedido_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('produto_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantidade', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('valor_unitario', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], name='itens_pedidos_pedido_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='itens_pedidos_pkey')
    )
    op.create_index('ix_itens_pedidos_id', 'itens_pedidos', ['id'], unique=False)
    op.create_table('caixa',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('caixa_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('data_abertura', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('valor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='caixa_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('pedidos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('caixa_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data_criacao', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('data_atualizacao', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('metodo_pagamento', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('valor_total', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('observacoes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['caixa_id'], ['caixa.id'], name='pedidos_caixa_id_fkey'),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name='pedidos_cliente_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='pedidos_pkey')
    )
    op.create_index('ix_pedidos_id', 'pedidos', ['id'], unique=False)
    op.create_table('clientes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('telefone', sa.VARCHAR(length=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='clientes_pkey')
    )
    op.create_index('ix_clientes_id', 'clientes', ['id'], unique=False)
    op.create_table('produtos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('categoria_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cod_pdv', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('preco_custo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('preco_venda', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('medida', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('estoque', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('estoque_min', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sit_estoque', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('ficha_tecnica', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('status_venda', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('imagem_name', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('imagem', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], name='produtos_categoria_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='produtos_pkey'),
    sa.UniqueConstraint('cod_pdv', name='produtos_cod_pdv_key')
    )
    # ### end Alembic commands ###
