"""criando nova coluna em itens para ordem

Revision ID: 453826f22a90
Revises: 6cc6e405fec3
Create Date: 2026-02-13 03:06:22.855480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '453826f22a90'
down_revision: Union[str, None] = '6cc6e405fec3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedido_itens', sa.Column('ordem_criacao', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedido_itens', 'ordem_criacao')
    # ### end Alembic commands ###
