"""Big Bang

Revision ID: 4c4821342196
Revises: 
Create Date: 2026-02-20 14:41:56.571236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c4821342196'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carrinhos',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('estabelecimento_id', sa.UUID(), nullable=False),
    sa.Column('produto_id', sa.UUID(), nullable=False),
    sa.Column('cod_pdv', sa.String(length=20), nullable=False),
    sa.Column('categoria', sa.String(length=30), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('preco_custo', sa.Float(), nullable=False),
    sa.Column('preco_venda', sa.Float(), nullable=False),
    sa.Column('medida', sa.String(length=2), nullable=False),
    sa.Column('estoque', sa.Integer(), nullable=False),
    sa.Column('estoque_min', sa.Integer(), nullable=False),
    sa.Column('sit_estoque', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=False),
    sa.Column('ficha_tecnica', sa.String(length=300), nullable=True),
    sa.Column('status_venda', sa.String(length=20), nullable=False),
    sa.Column('imagem_url', sa.String(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'estabelecimento_id', 'produto_id')
    )
    op.create_table('estabelecimentos',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=200), nullable=True),
    sa.Column('documento', sa.String(length=20), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('plano', sa.String(length=50), nullable=True),
    sa.Column('limite_usuarios', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('data_expiracao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subdominio', sa.String(length=100), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estabelecimentos_documento'), 'estabelecimentos', ['documento'], unique=True)
    op.create_index(op.f('ix_estabelecimentos_id'), 'estabelecimentos', ['id'], unique=False)
    op.create_index(op.f('ix_estabelecimentos_subdominio'), 'estabelecimentos', ['subdominio'], unique=True)
    op.create_table('caixa',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('estabelecimento_id', sa.UUID(), nullable=False),
    sa.Column('data_abertura', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_caixa_estabelecimento_id'), 'caixa', ['estabelecimento_id'], unique=False)
    op.create_table('categorias',
    sa.Column('id_categoria', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('estabelecimento_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], ),
    sa.PrimaryKeyConstraint('id_categoria'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_categorias_estabelecimento_id'), 'categorias', ['estabelecimento_id'], unique=False)
    op.create_table('clientes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('estabelecimento_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('telefone', sa.String(length=11), nullable=False),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_estabelecimento_id'), 'clientes', ['estabelecimento_id'], unique=False)
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_table('mesas',
    sa.Column('id_mesa', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('estabelecimento_id', sa.UUID(), nullable=False),
    sa.Column('caixa_id', sa.UUID(), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['caixa_id'], ['caixa.id'], ),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], ),
    sa.PrimaryKeyConstraint('id_mesa')
    )
    op.create_index(op.f('ix_mesas_caixa_id'), 'mesas', ['caixa_id'], unique=False)
    op.create_index(op.f('ix_mesas_estabelecimento_id'), 'mesas', ['estabelecimento_id'], unique=False)
    op.create_index(op.f('ix_mesas_id_mesa'), 'mesas', ['id_mesa'], unique=False)
    op.create_table('pedidos',
    sa.Column('id_pedido', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('estabelecimento_id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('caixa_id', sa.UUID(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('metodo_pagamento', sa.String(length=50), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['caixa_id'], ['caixa.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], ),
    sa.PrimaryKeyConstraint('id_pedido')
    )
    op.create_index(op.f('ix_pedidos_estabelecimento_id'), 'pedidos', ['estabelecimento_id'], unique=False)
    op.create_index(op.f('ix_pedidos_id_pedido'), 'pedidos', ['id_pedido'], unique=False)
    op.create_table('produtos',
    sa.Column('id_produto', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('estabelecimento_id', sa.UUID(), nullable=False),
    sa.Column('categoria_id', sa.UUID(), nullable=False),
    sa.Column('cod_pdv', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('preco_custo', sa.Float(), nullable=False),
    sa.Column('preco_venda', sa.Float(), nullable=False),
    sa.Column('medida', sa.String(length=2), nullable=False),
    sa.Column('estoque', sa.Integer(), nullable=False),
    sa.Column('estoque_min', sa.Integer(), nullable=False),
    sa.Column('sit_estoque', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=True),
    sa.Column('ficha_tecnica', sa.String(length=300), nullable=True),
    sa.Column('status_venda', sa.String(length=20), nullable=False),
    sa.Column('imagem_name', sa.String(length=300), nullable=True),
    sa.Column('imagem', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id_categoria'], ),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], ),
    sa.PrimaryKeyConstraint('id_produto'),
    sa.UniqueConstraint('cod_pdv')
    )
    op.create_index(op.f('ix_produtos_estabelecimento_id'), 'produtos', ['estabelecimento_id'], unique=False)
    op.create_table('enderecos_pedidos',
    sa.Column('id_endereco_pedido', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('estabelecimento_id', sa.UUID(), nullable=False),
    sa.Column('pedido_id', sa.UUID(), nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.Column('endereco', sa.String(length=200), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('bairro', sa.String(length=100), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.Column('complemento', sa.String(length=200), nullable=False),
    sa.Column('referencia', sa.String(length=200), nullable=True),
    sa.Column('taxa_entrega', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id_pedido'], ),
    sa.PrimaryKeyConstraint('id_endereco_pedido'),
    sa.UniqueConstraint('pedido_id')
    )
    op.create_index(op.f('ix_enderecos_pedidos_estabelecimento_id'), 'enderecos_pedidos', ['estabelecimento_id'], unique=False)
    op.create_index(op.f('ix_enderecos_pedidos_id_endereco_pedido'), 'enderecos_pedidos', ['id_endereco_pedido'], unique=False)
    op.create_table('itens_pedidos',
    sa.Column('id_itens_pedido', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('estabelecimento_id', sa.UUID(), nullable=False),
    sa.Column('pedido_id', sa.UUID(), nullable=False),
    sa.Column('produto_id', sa.UUID(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('valor_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id_pedido'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id_produto'], ),
    sa.PrimaryKeyConstraint('id_itens_pedido')
    )
    op.create_index(op.f('ix_itens_pedidos_estabelecimento_id'), 'itens_pedidos', ['estabelecimento_id'], unique=False)
    op.create_index(op.f('ix_itens_pedidos_id_itens_pedido'), 'itens_pedidos', ['id_itens_pedido'], unique=False)
    op.create_index(op.f('ix_itens_pedidos_pedido_id'), 'itens_pedidos', ['pedido_id'], unique=False)
    op.create_index(op.f('ix_itens_pedidos_produto_id'), 'itens_pedidos', ['produto_id'], unique=False)
    op.create_table('pedidos_mesa',
    sa.Column('id_pedido_mesa', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('estabelecimento_id', sa.UUID(), nullable=False),
    sa.Column('mesa_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('data_criacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valor_total', sa.Float(), nullable=False),
    sa.Column('quantidade_itens', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], ),
    sa.ForeignKeyConstraint(['mesa_id'], ['mesas.id_mesa'], ),
    sa.PrimaryKeyConstraint('id_pedido_mesa')
    )
    op.create_index(op.f('ix_pedidos_mesa_estabelecimento_id'), 'pedidos_mesa', ['estabelecimento_id'], unique=False)
    op.create_index(op.f('ix_pedidos_mesa_id_pedido_mesa'), 'pedidos_mesa', ['id_pedido_mesa'], unique=False)
    op.create_index(op.f('ix_pedidos_mesa_mesa_id'), 'pedidos_mesa', ['mesa_id'], unique=False)
    op.create_table('pedido_itens',
    sa.Column('id_itens_mesa', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('estabelecimento_id', sa.UUID(), nullable=False),
    sa.Column('pedido_id', sa.UUID(), nullable=False),
    sa.Column('produto_id', sa.UUID(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('valor_unitario', sa.Float(), nullable=False),
    sa.Column('valor_total', sa.Float(), nullable=False),
    sa.Column('ordem_criacao', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos_mesa.id_pedido_mesa'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id_produto'], ),
    sa.PrimaryKeyConstraint('id_itens_mesa')
    )
    op.create_index(op.f('ix_pedido_itens_estabelecimento_id'), 'pedido_itens', ['estabelecimento_id'], unique=False)
    op.create_index(op.f('ix_pedido_itens_pedido_id'), 'pedido_itens', ['pedido_id'], unique=False)
    op.create_index(op.f('ix_pedido_itens_produto_id'), 'pedido_itens', ['produto_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pedido_itens_produto_id'), table_name='pedido_itens')
    op.drop_index(op.f('ix_pedido_itens_pedido_id'), table_name='pedido_itens')
    op.drop_index(op.f('ix_pedido_itens_estabelecimento_id'), table_name='pedido_itens')
    op.drop_table('pedido_itens')
    op.drop_index(op.f('ix_pedidos_mesa_mesa_id'), table_name='pedidos_mesa')
    op.drop_index(op.f('ix_pedidos_mesa_id_pedido_mesa'), table_name='pedidos_mesa')
    op.drop_index(op.f('ix_pedidos_mesa_estabelecimento_id'), table_name='pedidos_mesa')
    op.drop_table('pedidos_mesa')
    op.drop_index(op.f('ix_itens_pedidos_produto_id'), table_name='itens_pedidos')
    op.drop_index(op.f('ix_itens_pedidos_pedido_id'), table_name='itens_pedidos')
    op.drop_index(op.f('ix_itens_pedidos_id_itens_pedido'), table_name='itens_pedidos')
    op.drop_index(op.f('ix_itens_pedidos_estabelecimento_id'), table_name='itens_pedidos')
    op.drop_table('itens_pedidos')
    op.drop_index(op.f('ix_enderecos_pedidos_id_endereco_pedido'), table_name='enderecos_pedidos')
    op.drop_index(op.f('ix_enderecos_pedidos_estabelecimento_id'), table_name='enderecos_pedidos')
    op.drop_table('enderecos_pedidos')
    op.drop_index(op.f('ix_produtos_estabelecimento_id'), table_name='produtos')
    op.drop_table('produtos')
    op.drop_index(op.f('ix_pedidos_id_pedido'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_estabelecimento_id'), table_name='pedidos')
    op.drop_table('pedidos')
    op.drop_index(op.f('ix_mesas_id_mesa'), table_name='mesas')
    op.drop_index(op.f('ix_mesas_estabelecimento_id'), table_name='mesas')
    op.drop_index(op.f('ix_mesas_caixa_id'), table_name='mesas')
    op.drop_table('mesas')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_estabelecimento_id'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_categorias_estabelecimento_id'), table_name='categorias')
    op.drop_table('categorias')
    op.drop_index(op.f('ix_caixa_estabelecimento_id'), table_name='caixa')
    op.drop_table('caixa')
    op.drop_index(op.f('ix_estabelecimentos_subdominio'), table_name='estabelecimentos')
    op.drop_index(op.f('ix_estabelecimentos_id'), table_name='estabelecimentos')
    op.drop_index(op.f('ix_estabelecimentos_documento'), table_name='estabelecimentos')
    op.drop_table('estabelecimentos')
    op.drop_table('carrinhos')
    # ### end Alembic commands ###
