"""adicionando duas novas coluna na tabela mesas

Revision ID: 5162095f9fc5
Revises: cb4decc56855
Create Date: 2026-02-04 23:35:40.995252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5162095f9fc5'
down_revision: Union[str, None] = 'cb4decc56855'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos_mesa', sa.Column('valor_total', sa.Float(), nullable=False))
    op.add_column('pedidos_mesa', sa.Column('quantidade_itens', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedidos_mesa', 'quantidade_itens')
    op.drop_column('pedidos_mesa', 'valor_total')
    # ### end Alembic commands ###
