"""acrescentando coluna valor_total em mesa

Revision ID: 6cc6e405fec3
Revises: 5162095f9fc5
Create Date: 2026-02-12 22:16:52.068967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cc6e405fec3'
down_revision: Union[str, None] = '5162095f9fc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedido_itens', sa.Column('valor_total', sa.Float(), nullable=False))
    op.create_foreign_key(None, 'pedido_itens', 'produtos', ['produto_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pedido_itens', type_='foreignkey')
    op.drop_column('pedido_itens', 'valor_total')
    # ### end Alembic commands ###
