"""initial creation

Revision ID: 9302d1897a39
Revises: 
Create Date: 2025-11-01 20:14:12.279204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9302d1897a39'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('categoria', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('categoria')
    )
    op.create_table('products',
    sa.Column('cod_sistema', sa.Integer(), nullable=False),
    sa.Column('cod_pdv', sa.String(length=20), nullable=False),
    sa.Column('categoria', sa.String(length=30), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('preco_custo', sa.Float(), nullable=False),
    sa.Column('preco_venda', sa.Float(), nullable=False),
    sa.Column('medida', sa.String(length=2), nullable=False),
    sa.Column('estoque', sa.Integer(), nullable=False),
    sa.Column('estoque_min', sa.Integer(), nullable=False),
    sa.Column('sit_estoque', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=False),
    sa.Column('ficha_tecnica', sa.String(length=300), nullable=True),
    sa.Column('status_venda', sa.String(length=20), nullable=False),
    sa.Column('imagem_url', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('cod_sistema')
    )
    op.create_table('users',
    sa.Column('cliente', sa.String(length=100), nullable=False),
    sa.Column('telefone', sa.String(length=11), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.Column('endereco', sa.String(length=200), nullable=False),
    sa.Column('bairro', sa.String(length=100), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('complemento', sa.String(length=200), nullable=False),
    sa.Column('referencia', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('telefone'),
    sa.UniqueConstraint('email')
    )
    op.create_table('carrinhos',
    sa.Column('cod_sistema', sa.Integer(), nullable=False),
    sa.Column('cod_pdv', sa.String(length=20), nullable=False),
    sa.Column('categoria', sa.String(length=30), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('preco_custo', sa.Float(), nullable=False),
    sa.Column('preco_venda', sa.Float(), nullable=False),
    sa.Column('medida', sa.String(length=2), nullable=False),
    sa.Column('estoque', sa.Integer(), nullable=False),
    sa.Column('estoque_min', sa.Integer(), nullable=False),
    sa.Column('sit_estoque', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=False),
    sa.Column('ficha_tecnica', sa.String(length=300), nullable=True),
    sa.Column('status_venda', sa.String(length=20), nullable=False),
    sa.Column('imagem_url', sa.String(length=300), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('cod_sistema')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carrinhos')
    op.drop_table('users')
    op.drop_table('products')
    op.drop_table('categories')
    # ### end Alembic commands ###
