"""criando tabela Mesas

Revision ID: cb4decc56855
Revises: 97d7bc84424b
Create Date: 2026-02-04 23:04:22.709589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb4decc56855'
down_revision: Union[str, None] = '97d7bc84424b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mesas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caixa_id', sa.Integer(), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['caixa_id'], ['caixa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mesas_id'), 'mesas', ['id'], unique=False)
    op.create_table('pedidos_mesa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mesa_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('data_criacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mesa_id'], ['mesas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedidos_mesa_id'), 'pedidos_mesa', ['id'], unique=False)
    op.create_table('pedido_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('valor_unitario', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos_mesa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedido_itens_id'), 'pedido_itens', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pedido_itens_id'), table_name='pedido_itens')
    op.drop_table('pedido_itens')
    op.drop_index(op.f('ix_pedidos_mesa_id'), table_name='pedidos_mesa')
    op.drop_table('pedidos_mesa')
    op.drop_index(op.f('ix_mesas_id'), table_name='mesas')
    op.drop_table('mesas')
    # ### end Alembic commands ###
