"""Incluindo tabelas

Revision ID: dd6b0fb4f78e
Revises: 9685bd82d0be
Create Date: 2025-12-22 21:41:17.757511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd6b0fb4f78e'
down_revision: Union[str, None] = '9685bd82d0be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caixa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_abertura', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carrinhos',
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('cod_pdv', sa.String(length=20), nullable=False),
    sa.Column('categoria', sa.String(length=30), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('preco_custo', sa.Float(), nullable=False),
    sa.Column('preco_venda', sa.Float(), nullable=False),
    sa.Column('medida', sa.String(length=2), nullable=False),
    sa.Column('estoque', sa.Integer(), nullable=False),
    sa.Column('estoque_min', sa.Integer(), nullable=False),
    sa.Column('sit_estoque', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=False),
    sa.Column('ficha_tecnica', sa.String(length=300), nullable=True),
    sa.Column('status_venda', sa.String(length=20), nullable=False),
    sa.Column('imagem_url', sa.String(length=300), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('produto_id')
    )
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('telefone', sa.String(length=11), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_table('estabelecimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('endereco', sa.String(length=200), nullable=False),
    sa.Column('instagram', sa.String(length=100), nullable=True),
    sa.Column('telefone', sa.String(length=15), nullable=False),
    sa.Column('logo_base64', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estabelecimento_id'), 'estabelecimento', ['id'], unique=False)
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('caixa_id', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('metodo_pagamento', sa.String(length=50), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['caixa_id'], ['caixa.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedidos_id'), 'pedidos', ['id'], unique=False)
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('cod_pdv', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('preco_custo', sa.Float(), nullable=False),
    sa.Column('preco_venda', sa.Float(), nullable=False),
    sa.Column('medida', sa.String(length=2), nullable=False),
    sa.Column('estoque', sa.Integer(), nullable=False),
    sa.Column('estoque_min', sa.Integer(), nullable=False),
    sa.Column('sit_estoque', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=True),
    sa.Column('ficha_tecnica', sa.String(length=300), nullable=True),
    sa.Column('status_venda', sa.String(length=20), nullable=False),
    sa.Column('imagem_name', sa.String(length=300), nullable=True),
    sa.Column('imagem', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cod_pdv')
    )
    op.create_table('enderecos_pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.Column('endereco', sa.String(length=200), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('bairro', sa.String(length=100), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.Column('complemento', sa.String(length=200), nullable=False),
    sa.Column('referencia', sa.String(length=200), nullable=True),
    sa.Column('taxa_entrega', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pedido_id')
    )
    op.create_index(op.f('ix_enderecos_pedidos_id'), 'enderecos_pedidos', ['id'], unique=False)
    op.create_table('itens_pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('valor_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itens_pedidos_id'), 'itens_pedidos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_itens_pedidos_id'), table_name='itens_pedidos')
    op.drop_table('itens_pedidos')
    op.drop_index(op.f('ix_enderecos_pedidos_id'), table_name='enderecos_pedidos')
    op.drop_table('enderecos_pedidos')
    op.drop_table('produtos')
    op.drop_index(op.f('ix_pedidos_id'), table_name='pedidos')
    op.drop_table('pedidos')
    op.drop_index(op.f('ix_estabelecimento_id'), table_name='estabelecimento')
    op.drop_table('estabelecimento')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_table('categorias')
    op.drop_table('carrinhos')
    op.drop_table('caixa')
    # ### end Alembic commands ###
