"""correção quantidade de characters da coluna image_url, banco carrinhos

Revision ID: f3dccc36758d
Revises: dd6b0fb4f78e
Create Date: 2025-12-31 16:11:19.944282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3dccc36758d'
down_revision: Union[str, None] = 'dd6b0fb4f78e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
