"""retirando coluna tamanho da tabela produto

Revision ID: 06e5064fbb39
Revises: 3725fec9138b
Create Date: 2026-04-03 18:25:43.430744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06e5064fbb39'
down_revision: Union[str, None] = '3725fec9138b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produtos', 'tamanho')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('tamanho', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
