"""criação da coluna tamanho

Revision ID: 0a6d07b83940
Revises: 35d108cd5c04
Create Date: 2026-04-15 03:09:26.406434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a6d07b83940'
down_revision: Union[str, None] = '35d108cd5c04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('impressoras', sa.Column('tamanho', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('impressoras', 'tamanho')
    # ### end Alembic commands ###
