"""atualizações de padrão primary_key

Revision ID: 29d797dad314
Revises: e89903927f33
Create Date: 2026-04-01 03:56:46.542332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29d797dad314'
down_revision: Union[str, None] = 'e89903927f33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('categorias_nome_key', 'categorias', type_='unique')
    op.create_unique_constraint('uix_categoria_nome_estabelecimento', 'categorias', ['estabelecimento_id', 'nome'])
    op.drop_constraint('produtos_cod_pdv_key', 'produtos', type_='unique')
    op.create_unique_constraint('uix_cod_pdv_estabelecimento', 'produtos', ['estabelecimento_id', 'cod_pdv'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_cod_pdv_estabelecimento', 'produtos', type_='unique')
    op.create_unique_constraint('produtos_cod_pdv_key', 'produtos', ['cod_pdv'])
    op.drop_constraint('uix_categoria_nome_estabelecimento', 'categorias', type_='unique')
    op.create_unique_constraint('categorias_nome_key', 'categorias', ['nome'])
    # ### end Alembic commands ###
