"""criação das tabelas fretes e geo

Revision ID: 2f72139a99c0
Revises: 92c844fe2ee2
Create Date: 2026-04-19 05:56:59.653062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f72139a99c0'
down_revision: Union[str, None] = '92c844fe2ee2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geolocalizacao',
    sa.Column('id_geoloc', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('estabelecimento_id', sa.UUID(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('long', sa.Float(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], ),
    sa.PrimaryKeyConstraint('id_geoloc')
    )
    op.create_index(op.f('ix_geolocalizacao_estabelecimento_id'), 'geolocalizacao', ['estabelecimento_id'], unique=False)
    op.create_index(op.f('ix_geolocalizacao_id_geoloc'), 'geolocalizacao', ['id_geoloc'], unique=False)
    op.create_table('taxas_de_entregas',
    sa.Column('id_frete_taxa', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('estabelecimento_id', sa.UUID(), nullable=False),
    sa.Column('km_minimo', sa.Float(), nullable=False),
    sa.Column('km_maximo', sa.Float(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], ),
    sa.PrimaryKeyConstraint('id_frete_taxa')
    )
    op.create_index(op.f('ix_taxas_de_entregas_estabelecimento_id'), 'taxas_de_entregas', ['estabelecimento_id'], unique=False)
    op.create_index(op.f('ix_taxas_de_entregas_id_frete_taxa'), 'taxas_de_entregas', ['id_frete_taxa'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_taxas_de_entregas_id_frete_taxa'), table_name='taxas_de_entregas')
    op.drop_index(op.f('ix_taxas_de_entregas_estabelecimento_id'), table_name='taxas_de_entregas')
    op.drop_table('taxas_de_entregas')
    op.drop_index(op.f('ix_geolocalizacao_id_geoloc'), table_name='geolocalizacao')
    op.drop_index(op.f('ix_geolocalizacao_estabelecimento_id'), table_name='geolocalizacao')
    op.drop_table('geolocalizacao')
    # ### end Alembic commands ###
