"""adicionando a coluna cor_layout em estabelecimento

Revision ID: 32c74f7dcd3b
Revises: 55ec0259b5e2
Create Date: 2026-03-25 00:38:44.682909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32c74f7dcd3b'
down_revision: Union[str, None] = '55ec0259b5e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estabelecimentos', sa.Column('cor_layout', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('estabelecimentos', 'cor_layout')
    # ### end Alembic commands ###
