"""adicionando a coluna produto_id

Revision ID: 3725fec9138b
Revises: 6f735c2cc0cf
Create Date: 2026-04-03 10:11:15.073963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3725fec9138b'
down_revision: Union[str, None] = '6f735c2cc0cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aux_tamanhos', sa.Column('produto_id', sa.UUID(), nullable=False))
    op.create_unique_constraint('uix_tamanho_produto', 'aux_tamanhos', ['produto_id', 'tamanho'])
    op.create_foreign_key(None, 'aux_tamanhos', 'produtos', ['produto_id'], ['id_produto'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'aux_tamanhos', type_='foreignkey')
    op.drop_constraint('uix_tamanho_produto', 'aux_tamanhos', type_='unique')
    op.drop_column('aux_tamanhos', 'produto_id')
    # ### end Alembic commands ###
