"""correção da tabela entrega pedidos novamente

Revision ID: 4a4ae0da2d9e
Revises: e52109124f17
Create Date: 2026-04-20 06:00:38.770492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a4ae0da2d9e'
down_revision: Union[str, None] = 'e52109124f17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enderecos_pedidos', sa.Column('distancia', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('enderecos_pedidos', sa.Column('faixa_km', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enderecos_pedidos', 'faixa_km')
    op.drop_column('enderecos_pedidos', 'distancia')
    # ### end Alembic commands ###
