"""adicionando coluna descricao

Revision ID: 55ec0259b5e2
Revises: bdc19637d8fb
Create Date: 2026-03-25 00:12:29.413219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55ec0259b5e2'
down_revision: Union[str, None] = 'bdc19637d8fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estabelecimentos', sa.Column('descricao', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('estabelecimentos', 'descricao')
    # ### end Alembic commands ###
