"""mudanca nullable da coluna dia_semana

Revision ID: 5c87a96bb5df
Revises: 39f8d8600fed
Create Date: 2026-03-27 13:12:51.614755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c87a96bb5df'
down_revision: Union[str, None] = '39f8d8600fed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('funcionamento_horarios', 'dia_semana',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('ix_funcionamento_horarios_estabelecimento_id', table_name='funcionamento_horarios')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_funcionamento_horarios_estabelecimento_id', 'funcionamento_horarios', ['estabelecimento_id'], unique=False)
    op.alter_column('funcionamento_horarios', 'dia_semana',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
