"""atribuindo a tabela tamanhos

Revision ID: 6f735c2cc0cf
Revises: 29d797dad314
Create Date: 2026-04-03 09:45:54.998743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f735c2cc0cf'
down_revision: Union[str, None] = '29d797dad314'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aux_tamanhos',
    sa.Column('tamanho_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('estabelecimento_id', sa.UUID(), nullable=False),
    sa.Column('tamanho', sa.String(length=300), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], ),
    sa.PrimaryKeyConstraint('tamanho_id')
    )
    op.create_index(op.f('ix_aux_tamanhos_estabelecimento_id'), 'aux_tamanhos', ['estabelecimento_id'], unique=False)
    op.add_column('produtos', sa.Column('tamanho', sa.String(), nullable=True))
    op.add_column('produtos', sa.Column('dias_vendas', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produtos', 'dias_vendas')
    op.drop_column('produtos', 'tamanho')
    op.drop_index(op.f('ix_aux_tamanhos_estabelecimento_id'), table_name='aux_tamanhos')
    op.drop_table('aux_tamanhos')
    # ### end Alembic commands ###
