"""nova coluna tamanho em itens

Revision ID: 92c844fe2ee2
Revises: 0a6d07b83940
Create Date: 2026-04-16 01:08:02.085219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92c844fe2ee2'
down_revision: Union[str, None] = '0a6d07b83940'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itens_pedidos', sa.Column('tamanho', sa.String(length=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('itens_pedidos', 'tamanho')
    # ### end Alembic commands ###
