"""adicionando a tabela impressoras

Revision ID: 977abfa0da8a
Revises: 7f9179576a5c
Create Date: 2026-03-19 11:26:59.836987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '977abfa0da8a'
down_revision: Union[str, None] = '7f9179576a5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('impressoras',
    sa.Column('impressora_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('estabelecimento_id', sa.UUID(), nullable=False),
    sa.Column('data_adicao', sa.DateTime(timezone=True), nullable=True, serve_default=sa.text('now()')),
    sa.Column('impressora', sa.String(length=100), nullable=True),
    sa.Column('padrao', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], ),
    sa.PrimaryKeyConstraint('impressora_id')
    )
    op.create_index(op.f('ix_impressoras_estabelecimento_id'), 'impressoras', ['estabelecimento_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_impressoras_estabelecimento_id'), table_name='impressoras')
    op.drop_table('impressoras')
    # ### end Alembic commands ###
