"""criação da coluna redirecionamento

Revision ID: b6bf44e14600
Revises: 5c87a96bb5df
Create Date: 2026-03-31 21:36:46.500299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6bf44e14600'
down_revision: Union[str, None] = '5c87a96bb5df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estabelecimentos', sa.Column('redirecionamento', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('estabelecimentos', 'redirecionamento')
    # ### end Alembic commands ###
