"""correção da tabela caixa

Revision ID: ba1210b1af85
Revises: 7f1d1203e3fa
Create Date: 2026-03-22 02:43:03.725118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba1210b1af85'
down_revision: Union[str, None] = '7f1d1203e3fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('caixa', sa.Column('valor_inicial', sa.Float(), nullable=False))
    op.add_column('caixa', sa.Column('valor_final', sa.Float(), nullable=False))
    op.add_column('caixa', sa.Column('data_fechamento', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('caixa', 'valor')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('caixa', sa.Column('valor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('caixa', 'data_fechamento')
    op.drop_column('caixa', 'valor_final')
    op.drop_column('caixa', 'valor_inicial')
    # ### end Alembic commands ###
