"""criação da coluna valor total em Item Pedido

Revision ID: ccfe75492401
Revises: f9920f8815fd
Create Date: 2026-03-11 23:10:31.225028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccfe75492401'
down_revision: Union[str, None] = 'f9920f8815fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itens_pedidos', sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('itens_pedidos', 'valor_total')
    # ### end Alembic commands ###
