"""criando tabelas de horario de funcionamento

Revision ID: de7f229fbb9c
Revises: 32c74f7dcd3b
Create Date: 2026-03-26 15:41:32.011158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de7f229fbb9c'
down_revision: Union[str, None] = '32c74f7dcd3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('excecao_horarios',
    sa.Column('id_horarios_exce', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('estabelecimento_id', sa.UUID(), nullable=False),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('hora_abertura', sa.Time(), nullable=True),
    sa.Column('hora_fechamento', sa.Time(), nullable=True),
    sa.Column('fechado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], ),
    sa.PrimaryKeyConstraint('id_horarios_exce')
    )
    op.create_index(op.f('ix_excecao_horarios_estabelecimento_id'), 'excecao_horarios', ['estabelecimento_id'], unique=False)
    op.create_index(op.f('ix_excecao_horarios_id_horarios_exce'), 'excecao_horarios', ['id_horarios_exce'], unique=False)
    op.create_table('funcionamento_horarios',
    sa.Column('id_horarios_func', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('estabelecimento_id', sa.UUID(), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=True),
    sa.Column('hora_abertura', sa.Time(), nullable=True),
    sa.Column('hora_fechamento', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], ),
    sa.PrimaryKeyConstraint('id_horarios_func')
    )
    op.create_index(op.f('ix_funcionamento_horarios_estabelecimento_id'), 'funcionamento_horarios', ['estabelecimento_id'], unique=False)
    op.create_index(op.f('ix_funcionamento_horarios_id_horarios_func'), 'funcionamento_horarios', ['id_horarios_func'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_funcionamento_horarios_id_horarios_func'), table_name='funcionamento_horarios')
    op.drop_index(op.f('ix_funcionamento_horarios_estabelecimento_id'), table_name='funcionamento_horarios')
    op.drop_table('funcionamento_horarios')
    op.drop_index(op.f('ix_excecao_horarios_id_horarios_exce'), table_name='excecao_horarios')
    op.drop_index(op.f('ix_excecao_horarios_estabelecimento_id'), table_name='excecao_horarios')
    op.drop_table('excecao_horarios')
    # ### end Alembic commands ###
