"""alteração na tabela de coordenadas

Revision ID: e52109124f17
Revises: 2f72139a99c0
Create Date: 2026-04-20 02:43:38.584829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e52109124f17'
down_revision: Union[str, None] = '2f72139a99c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coordenadas',
    sa.Column('id_coordenadas', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('estabelecimento_id', sa.UUID(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], ),
    sa.PrimaryKeyConstraint('id_coordenadas')
    )
    op.create_index(op.f('ix_coordenadas_estabelecimento_id'), 'coordenadas', ['estabelecimento_id'], unique=False)
    op.create_index(op.f('ix_coordenadas_id_coordenadas'), 'coordenadas', ['id_coordenadas'], unique=False)
    op.drop_index('ix_geolocalizacao_estabelecimento_id', table_name='geolocalizacao')
    op.drop_index('ix_geolocalizacao_id_geoloc', table_name='geolocalizacao')
    op.drop_table('geolocalizacao')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geolocalizacao',
    sa.Column('id_geoloc', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('estabelecimento_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('long', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('ativo', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], name='geolocalizacao_estabelecimento_id_fkey'),
    sa.PrimaryKeyConstraint('id_geoloc', name='geolocalizacao_pkey')
    )
    op.create_index('ix_geolocalizacao_id_geoloc', 'geolocalizacao', ['id_geoloc'], unique=False)
    op.create_index('ix_geolocalizacao_estabelecimento_id', 'geolocalizacao', ['estabelecimento_id'], unique=False)
    op.drop_index(op.f('ix_coordenadas_id_coordenadas'), table_name='coordenadas')
    op.drop_index(op.f('ix_coordenadas_estabelecimento_id'), table_name='coordenadas')
    op.drop_table('coordenadas')
    # ### end Alembic commands ###
