"""adicao da coluna opcoes_pagamento

Revision ID: ea27b14a14d4
Revises: df05498898df
Create Date: 2026-03-09 22:46:50.841234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea27b14a14d4'
down_revision: Union[str, None] = 'df05498898df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos', sa.Column('opcoes_pagamento', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedidos', 'opcoes_pagamento')
    # ### end Alembic commands ###
